#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



########## Window Settings ##############
bspc config border_width         2
bspc config window_gap           10
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########## Border Colors #################
bspc config focused_border_color "#2E3440"
bspc config normal_border_color "#2E3440"

######### Program settings ################



######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 30

######## Picom ###################
picom  &

######## Wallpaper ####
nitrogen --restore &

######### Polybar ###############
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar main &
polybar workspaces &
polybar center_info &
polybar power_button &

### Personal Software ###
flameshot &
nm-applet &
